name: .NET 6.0
on:
  pull_request:
    branches: [ main ]

jobs:
  BuildAndTest:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
    - uses: cryptic-wizard/run-specflow-tests@v1.3.1
      with:
        test-assembly-path: Tests/bin/Release/net6.0
        test-assembly-dll: Tests.dll
        output-html: ProjectEulerTests.html
        framework: net6.0